/**
 * Old /help/[id] Help Center article ids -> the new merged /docs location. Per the documentation
 * consolidation, this corpus's useful substance was migrated into the single PawOS documentation
 * system rather than kept as a second, disconnected surface — every id redirects rather than
 * serving orphaned duplicate content. Ids with no direct migrated equivalent fall back to /docs.
 */
export const HELP_TO_DOCS_REDIRECTS: Record<string, string> = {
  'welcome-to-pawos': '/docs/getting-started/introduction',
  'first-launch': '/docs/getting-started/quickstart',
  'installing-pawos': '/docs/getting-started/installation',
  'navigation': '/docs/getting-started/quickstart',
  'workspaces': '/docs/concepts/workspaces',
  'creating-projects': '/docs/getting-started/first-workspace',
  'importing-projects': '/docs/getting-started/first-workspace',
  'history': '/docs/concepts/working-history',
  'project-health': '/docs/concepts/work-records',
  'ai-coding': '/docs/coding/overview',
  'code-review': '/docs/coding/planning-and-review',
  'debugging': '/docs/coding/testing-and-validation',
  'build-system': '/docs/coding/build-and-preview',
  'terminal': '/docs/coding/commands-and-terminal',
  'git-repositories': '/docs/coding/code-editing',
  'coding-canvas-vscode-integration': '/docs/coding/coding-workspace',
  'meet-paw': '/docs/companion/overview',
  'companion-behaviors': '/docs/companion/desktop-companion',
  'companion-memory': '/docs/companion/overview',
  'companion-permissions': '/docs/companion/permissions',
  'companion-studio': '/docs/companion/custom-companion',
  'personalities': '/docs/companion/custom-companion',
  'shared-companion': '/docs/companion/custom-companion',
  'voice-conversations': '/docs/companion/wake-word',
  'troubleshooting-companion': '/docs/troubleshooting/wont-start',
  'mobile': '/docs/mobile/overview',
  'devices': '/docs/mobile/connectivity',
  'offline-mode': '/docs/mobile/limitations',
  'communication-email': '/docs/connectors/google-workspace',
  'communication-calendar': '/docs/connectors/google-workspace',
  'draft-replies': '/docs/connectors/google-workspace',
  'meetings': '/docs/connectors/overview',
  'research-workspace': '/docs/coding/project-understanding',
  'website-analysis': '/docs/coding/project-understanding',
  'cloud-google': '/docs/connectors/google-workspace',
  'cloud-sync': '/docs/mobile/presence',
  'analytics-ai-usage': '/docs/billing/usage',
  'analytics-development': '/docs/coding/work-records',
  'analytics-productivity': '/docs/billing/usage',
  'summaries': '/docs/concepts/evidence',
  'account-required': '/docs/getting-started/installation',
  'account-security': '/docs/security/credentials',
  'account-usage': '/docs/billing/usage',
  'profile': '/docs/billing/subscriptions',
  'google-sign-in': '/docs/troubleshooting/authentication-problems',
  'paw-go': '/docs/billing/plans',
  'paw-pro': '/docs/billing/plans',
  'paw-pro-max': '/docs/billing/plans',
  'billing': '/docs/billing/payments',
  'backups': '/docs/security/credentials',
  'team': '/docs/billing/plans',
  'enterprise': '/docs/billing/plans',
  'security': '/docs/security/permissions',
  'privacy': '/docs/security/credentials',
  'keyboard-shortcuts': '/docs/getting-started/quickstart',
  'knowledge-base': '/docs',
  'desktop': '/docs/companion/desktop-companion',
};
