/**
 * Old flat /docs/[slug] and /docs/runtimes/[slug] paths -> new /docs/[section]/[slug].
 * Keeps any previously-shared link working instead of turning it into a 404.
 * Checked by the catch-all route before falling through to notFound().
 */
export const LEGACY_DOC_REDIRECTS: Record<string, string> = {
  'getting-started': '/docs/getting-started/introduction',
  'installation': '/docs/getting-started/installation',
  'system-requirements': '/docs/getting-started/system-requirements',
  'quick-start': '/docs/getting-started/quickstart',
  'companions': '/docs/companion/overview',
  'models': '/docs/reference/architecture',
  'voice': '/docs/companion/overview',
  'projects': '/docs/concepts/workspaces',
  'tasks': '/docs/concepts/working-history',
  'plans': '/docs/concepts/plans',
  'providers': '/docs/connectors/overview',
  'runtime-configuration': '/docs/reference/architecture',
  'billing-and-usage': '/docs/billing/plans',
  'referrals': '/docs/billing/credits',
  'enterprise-deployment': '/docs/billing/plans',
  'ci-cd': '/docs/connectors/other-connectors',
  'deployments': '/docs/connectors/other-connectors',
  'settings': '/docs/getting-started/quickstart',
  'security-architecture': '/docs/security/permissions',
  'privacy-and-data': '/docs/security/credentials',
  'troubleshooting': '/docs/troubleshooting/wont-start',
  'api-reference': '/docs/reference/api-reference',
  'keyboard-shortcuts': '/docs/getting-started/quickstart',
  'faq': '/docs/troubleshooting/wont-start',
  'glossary': '/docs/concepts/workspaces',
  'versioning': '/docs/reference/changelog',
  'migration-guides': '/docs/reference/changelog',
  'release-notes': '/docs/reference/changelog',
  'architecture-overview': '/docs/reference/architecture',
  'developer-documentation': '/docs/reference/architecture',
  'runtimes/universal-execution': '/docs/coding/commands-and-terminal',
  'runtimes/browser-runtime': '/docs/coding/build-and-preview',
  'runtimes/infrastructure-runtime': '/docs/connectors/other-connectors',
  'runtimes/communication-runtime': '/docs/companion/overview',
  'runtimes/companion-runtime': '/docs/companion/overview',
  'runtimes/governance-runtime': '/docs/security/permissions',
  'autonomous-ticket-resolution': '/docs/autonomous-work/overview',
};
