import { emailService } from './EmailService';

const PAWOS_WEB_BASE_URL = 'https://pawos.revantaai.com';

export type OtpPurpose = 'signup' | 'password-reset';

/**
 * Delivers a verification code generated by otp.ts. With local SMTP configured (a developer
 * .env) it sends directly; otherwise — every installed/Store build, which never ships SMTP
 * credentials — pawos-web sends it from its own server SMTP
 * (pawos-web/src/app/api/auth/send-verification-code/route.ts).
 */
export async function deliverOtp(
  email: string,
  params: { code: string; expiresInMinutes: number; purpose: OtpPurpose },
  deps: { fetchImpl?: typeof fetch; hasLocalSmtp?: () => boolean } = {}
): Promise<void> {
  const hasLocalSmtp = deps.hasLocalSmtp ?? (() => emailService.isConfigured());
  if (hasLocalSmtp()) {
    await emailService.sendOTP(email, { code: params.code, expiresInMinutes: params.expiresInMinutes });
    return;
  }

  const fetchImpl = deps.fetchImpl ?? fetch;
  let response: Response;
  try {
    response = await fetchImpl(`${PAWOS_WEB_BASE_URL}/api/auth/send-verification-code`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, code: params.code, expiresInMinutes: params.expiresInMinutes, purpose: params.purpose }),
    });
  } catch {
    throw new Error("Couldn't reach PawOS to send your verification code. Check your internet connection and try again.");
  }
  const payload = (await response.json().catch(() => ({}))) as { ok?: boolean; error?: string };
  if (!response.ok || !payload.ok) {
    throw new Error(payload.error || `We couldn't send your verification code (HTTP ${response.status}). Please try again.`);
  }
}
