import type { HelpArticle } from '../HelpArticleTypes';

export const CLOUD_ARTICLES: HelpArticle[] = [
  {
    id: 'cloud-google',
    category: 'cloud',
    title: 'Google',
    summary: 'Signing in to PawOS with your Google account.',
    overview:
      'Continue with Google signs you in to PawOS with your Google account — no separate password needed. ' +
      'It is used only to sign you in.',
    features: ['Sign in with your Google account'],
    howItWorks: 'Choosing "Continue with Google" on the sign-in screen opens Google’s own sign-in page, then returns you to PawOS signed in. It gives PawOS your name and email address — nothing from your Drive, Calendar or Gmail.',
    bestPractices: ['Choose the Google account you want linked to PawOS on Google’s sign-in page'],
    examples: [],
    troubleshooting: ['If Google Sign-In fails, check your internet connection and that you’re using a valid Google account'],
    requirements: ['An internet connection', 'A Google account'],
    permissions: ['Your name and email address, to sign you in'],
    relatedArticleIds: ['google-sign-in', 'cloud-sync'],
    relatedSettings: ['Account'],
    relatedApps: ['settings'],
    faq: [
      { question: 'What does PawOS get from my Google account?', answer: 'Your name and email address, to sign you in.' },
      { question: 'Does PawOS see my Google password?', answer: 'No — you sign in on Google’s own page.' },
    ],
    keywords: ['google', 'google sign in', 'continue with google'],
    aliases: ['Google', 'Continue with Google'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'cloud-sync',
    category: 'cloud',
    title: 'Cloud Sync',
    summary: 'What is stored in the cloud, and what stays on your computer.',
    overview:
      'PawOS keeps your work on your computer. Your account session — and, on Team and Enterprise plans, ' +
      'your organization and membership — are stored securely in the cloud so you can sign in anywhere. ' +
      'Settings, conversation history, companion memory and work history stay on the device they were created on.',
    features: ['Your account session, available wherever you sign in', 'Organization and membership data for Team and Enterprise accounts'],
    howItWorks: 'Your account session and organization membership are stored securely and isolated so only your own organization’s members can see organization data. Everything else stays as local files on each device.',
    bestPractices: ['Your settings and history live on each computer — sign in on another device to use the same account there'],
    examples: [],
    troubleshooting: [],
    requirements: ['An internet connection to sign in', 'A PawOS account'],
    permissions: [],
    relatedArticleIds: ['cloud-google', 'offline-mode', 'privacy'],
    relatedSettings: ['Account', 'Privacy'],
    relatedApps: ['settings'],
    faq: [{ question: 'What is stored in the cloud?', answer: 'Your account session and, on Team and Enterprise plans, your organization membership. Everything else stays on your computer.' }],
    keywords: ['cloud sync', 'sync', 'organization sync'],
    aliases: ['Cloud Sync'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'offline-mode',
    category: 'cloud',
    title: 'Offline Mode',
    summary: 'What still works when you have no internet connection.',
    overview:
      'PawOS fully functions offline for everything that doesn’t inherently need the internet: local companion ' +
      'interaction (outside of AI reasoning/voice, which need a configured provider), project and file work, ' +
      'git operations, and anything you’ve previously viewed. What genuinely requires a connection is AI ' +
      'reasoning/voice (needs a configured provider), cloud authentication, and Organization/Team features.',
    features: ['Full local project/git/file functionality with no connection', 'Companion visuals and idle behaviors work offline'],
    howItWorks: 'PawOS distinguishes local operations (which run entirely on-device) from cloud-dependent ones (sign-in, AI reasoning, organization data), so losing connectivity only affects the latter.',
    bestPractices: ['If you know you’ll be offline, sign in beforehand — reasoning and voice features need a connection when you use them'],
    examples: [],
    troubleshooting: ['If AI conversations stop responding, check your connection — reasoning/voice genuinely require it'],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['cloud-sync', 'cloud-google'],
    relatedSettings: [],
    relatedApps: ['settings'],
    faq: [{ question: 'Can I use PawOS with no internet at all?', answer: 'Yes, for local project/git/file work and basic companion visuals. AI reasoning/voice and cloud/organization features need a connection.' }],
    keywords: ['offline', 'offline mode', 'no internet'],
    aliases: ['Offline Mode'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
];
