/**
 * Event taxonomy for the Platform Runtime — PawOS's internal, admin-only
 * reliability system (never customer-facing). Every other PawOS runtime
 * reports into this taxonomy via `reportRuntimeEvent()` (PlatformEventBus.ts).
 *
 * Per the frozen "Platform Runtime — Final Architecture Review": this is the
 * event *shape* the design calls for, implemented as a plain additive
 * function call rather than a shared cross-runtime bus object every runtime
 * holds a reference to (see PlatformEventBus.ts's own doc comment).
 */

export type PlatformRuntimeName =
  | 'desktop'
  | 'execution'
  | 'coding'
  | 'intelligence'
  | 'planning'
  | 'conversation'
  | 'browser'
  | 'workspace'
  | 'memory'
  | 'organization'
  | 'connector'
  | 'mobilePresence'
  | 'billing'
  | 'voice'
  | 'companion'
  | 'communication'
  | 'platform';

export type PlatformEventSeverity = 'info' | 'warning' | 'error' | 'critical';

interface RuntimeEventBase {
  /** Unique id, auto-generated by reportRuntimeEvent — never supplied by callers. */
  id: string;
  /** Unix ms, auto-generated by reportRuntimeEvent — never supplied by callers. */
  timestamp: number;
  runtime: PlatformRuntimeName;
  severity: PlatformEventSeverity;
}

export interface RuntimeHealthEvent extends RuntimeEventBase {
  kind: 'health';
  status: 'ok' | 'degraded' | 'down';
  detail?: string;
}

export interface RuntimeErrorEvent extends RuntimeEventBase {
  kind: 'error';
  message: string;
  stack?: string;
  context?: Record<string, unknown>;
}

export interface RuntimeWarningEvent extends RuntimeEventBase {
  kind: 'warning';
  message: string;
  context?: Record<string, unknown>;
}

export interface RuntimePerformanceEvent extends RuntimeEventBase {
  kind: 'performance';
  metric: string;
  value: number;
  unit?: string;
}

export interface RuntimeRecoveryEvent extends RuntimeEventBase {
  kind: 'recovery';
  action: string;
  outcome: 'attempted' | 'succeeded' | 'failed';
  attempt: number;
}

export interface RuntimeValidationEvent extends RuntimeEventBase {
  kind: 'validation';
  step: string;
  outcome: 'passed' | 'failed' | 'skipped';
  detail?: string;
}

export interface RuntimeCrashEvent extends RuntimeEventBase {
  kind: 'crash';
  processType: 'main' | 'renderer' | 'gpu' | 'child';
  message: string;
  stack?: string;
}

export type RuntimeEvent =
  | RuntimeHealthEvent
  | RuntimeErrorEvent
  | RuntimeWarningEvent
  | RuntimePerformanceEvent
  | RuntimeRecoveryEvent
  | RuntimeValidationEvent
  | RuntimeCrashEvent;

/**
 * Plain `Omit` does not distribute over a union — `keyof RuntimeEvent` collapses
 * to only the fields common to every member, which would erase every
 * kind-specific field (message, status, metric, ...). This distributes Omit
 * over each union member individually instead, preserving discrimination.
 */
type DistributiveOmit<T, K extends keyof T> = T extends unknown ? Omit<T, K> : never;

/** What a caller supplies — id/timestamp are always assigned by the bus. */
export type RuntimeEventInput = DistributiveOmit<RuntimeEvent, 'id' | 'timestamp'>;
