import type { HelpArticle } from '../HelpArticleTypes';

export const ACCOUNT_ARTICLES: HelpArticle[] = [
  {
    id: 'account-required',
    category: 'account',
    title: 'Account Required',
    summary: 'PawOS requires a real account. Paw Go remains the free plan.',
    overview:
      'PawOS now requires a signed-in account. Paw Go remains the free authenticated plan, while paid plans ' +
      'unlock additional runtime access according to your entitlements.',
    features: ['Email, Google, and GitHub sign-in', 'Paw Go as the free authenticated plan', 'Real account-scoped billing, usage, and entitlement state'],
    howItWorks: 'Sign in or create an account on the auth screen. After authentication, PawOS starts you on Paw Go unless your account or organization grants a higher plan.',
    bestPractices: ['Use a real email or supported OAuth provider you control', 'Review Settings → Billing to confirm your current plan and runtime access'],
    examples: [{ title: 'Starting with Paw Go', steps: ['Open PawOS', 'Sign in with Email, Google, or GitHub', 'Use Paw Go planning, analysis, and guidance features', 'Upgrade only when you need paid runtime execution'] }],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['profile', 'account-security', 'devices'],
    relatedSettings: ['Account'],
    relatedApps: ['settings'],
    faq: [
      { question: 'Is there still a free plan?', answer: 'Yes. Paw Go is free, but it requires an authenticated account.' },
      { question: 'Can I continue without signing in?', answer: 'No. PawOS requires an account before the app opens.' },
    ],
    keywords: ['account required', 'paw go', 'free plan', 'sign in'],
    aliases: ['Account Required', 'Paw Go', 'Free plan'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'profile',
    category: 'account',
    title: 'Profile',
    summary: 'Your account name, email, and sign-out control.',
    overview: 'The Account settings tab shows your real signed-in name and email, and lets you sign out. It reflects your actual authentication provider honestly.',
    features: ['View your real account name and email', 'Sign out'],
    howItWorks: 'Open Settings → Account to see your profile details, sourced directly from your authentication session.',
    bestPractices: [],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['account-required', 'account-security'],
    relatedSettings: ['Account'],
    relatedApps: ['settings'],
    faq: [],
    keywords: ['profile', 'account profile'],
    aliases: ['Profile', 'Account'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 1,
  },
  {
    id: 'devices',
    category: 'account',
    title: 'Devices',
    summary: 'Pairing another device with a QR code — real infrastructure, built for future mobile use.',
    overview:
      'PawOS has a real device-pairing system: generate a QR code and a paired device registers itself against ' +
      'your account. This was built as generic pairing infrastructure with a future mobile companion in mind ' +
      '(see Mobile), and requires a real account.',
    features: ['QR-code-based device pairing', 'A real device registry per account'],
    howItWorks: 'Open Settings → Devices, generate a pairing QR code, and scan it from the other device to register it against your account.',
    bestPractices: ['Pair devices only from Settings you trust — a paired device is tied to your real account'],
    examples: [],
    troubleshooting: ['If pairing is unavailable, confirm you are signed into the correct account and plan'],
    requirements: ['A real PawOS account'],
    permissions: [],
    relatedArticleIds: ['account-required', 'mobile'],
    relatedSettings: ['Devices'],
    relatedApps: ['settings'],
    faq: [{ question: 'Can I pair devices without an account?', answer: 'No. Device pairing requires a real account.' }],
    keywords: ['devices', 'device pairing', 'qr code'],
    aliases: ['Devices', 'Pair device'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'account-usage',
    category: 'account',
    title: 'Usage',
    summary: 'Your real AI credit usage against your subscription tier.',
    overview: 'The Usage settings tab shows real, live credit consumption tracked against your tier’s monthly limit — the same underlying data shown in Analytics > AI Usage.',
    features: ['Real usage-this-period tracking', 'Tier-aware credit limit display'],
    howItWorks: 'Every credit-consuming AI action updates this same real usage number.',
    bestPractices: [],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    billing: 'Paw Go has a capped AI credit pool (real AI, planning/analysis only — no execution). Other tiers are currently uncapped until specific limits are finalized.',
    relatedArticleIds: ['analytics-ai-usage', 'paw-go'],
    relatedSettings: ['Usage'],
    relatedApps: ['settings', 'analytics'],
    faq: [],
    keywords: ['usage', 'account usage', 'credits'],
    aliases: ['Usage'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 1,
  },
  {
    id: 'account-security',
    category: 'account',
    title: 'Security',
    summary: 'Authentication and password reset for your account.',
    overview:
      'Account-level security covers real hashed passwords for email accounts, real Google OAuth, and a real ' +
      'Forgot Password → one-time code (OTP) → Set New Password flow.',
    features: ['Hashed password storage — never plaintext', 'Real Google OAuth', 'Forgot Password → OTP → Set New Password'],
    howItWorks: 'Choosing "Forgot password" sends a real one-time code to your email; entering it lets you set a new password.',
    bestPractices: ['Use a unique password for your PawOS account', 'Use the Forgot Password flow rather than trying to guess your old password'],
    examples: [{ title: 'Resetting a forgotten password', steps: ['Choose "Forgot password" on the sign-in screen', 'Enter your email', 'Enter the one-time code sent to you', 'Set a new password'] }],
    troubleshooting: ['If the OTP email doesn’t arrive, check spam and confirm the email address is correct'],
    requirements: ['A verified email for the OTP reset flow'],
    permissions: [],
    relatedArticleIds: ['profile', 'security', 'privacy'],
    relatedSettings: ['Account', 'Security'],
    relatedApps: ['settings'],
    faq: [{ question: 'Are my passwords stored in plaintext?', answer: 'No — passwords are hashed, never stored in plaintext.' }],
    keywords: ['security', 'password reset', 'otp', 'forgot password'],
    aliases: ['Forgot Password', 'Reset password'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
];
