import type { HelpArticle } from '../HelpArticleTypes';

export const ACCOUNT_ARTICLES: HelpArticle[] = [
  {
    id: 'guest-session',
    category: 'account',
    title: 'Guest Session',
    summary: 'Using PawOS with no account, and what that honestly means.',
    overview:
      'Guest mode is fully local: no cloud data, no fabricated subscription tier (the UI honestly shows ' +
      '"Guest Preview," never a made-up plan name), and no Organization/Team features, since those require a ' +
      'real signed-in account. You can upgrade to a real account (Google or Email) at any time without losing ' +
      'your local data.',
    features: ['No account required to use PawOS', 'Strictly local data, nothing uploaded', 'Honest UI — never shows a fake tier or fake usage numbers', 'Upgrade to a real account anytime, keeping local data'],
    howItWorks: 'Choosing "Continue as Guest" on the auth screen skips sign-in entirely. All your data (settings, companion, history) stays local to this device until and unless you upgrade to a real account.',
    bestPractices: ['Use Guest mode to try PawOS risk-free', 'Upgrade to a real account before you need Devices pairing or Organization/Team features, since those require one'],
    examples: [{ title: 'Upgrading from Guest to a real account', steps: ['Open Settings → Account', 'Choose to create a real account (Google or Email)', 'Complete sign-in', 'Your local data carries over to the new account'] }],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['profile', 'account-security', 'devices'],
    relatedSettings: ['Account'],
    relatedApps: ['settings'],
    faq: [
      { question: 'Does Guest mode cost anything?', answer: 'No — it is free and requires no account.' },
      { question: 'Will I lose my data if I upgrade from Guest?', answer: 'No — upgrading to a real account carries your existing local data over.' },
    ],
    keywords: ['guest', 'guest session', 'guest mode'],
    aliases: ['Guest Session', 'Continue as Guest', 'Guest Preview'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'profile',
    category: 'account',
    title: 'Profile',
    summary: 'Your account name, email, and sign-out control.',
    overview: 'The Account settings tab shows your real signed-in name and email, and lets you sign out. It reflects your actual authentication provider (Guest, Google, or Email) honestly.',
    features: ['View your real account name and email', 'Sign out'],
    howItWorks: 'Open Settings → Account to see your profile details, sourced directly from your authentication session.',
    bestPractices: [],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['guest-session', 'account-security'],
    relatedSettings: ['Account'],
    relatedApps: ['settings'],
    faq: [],
    keywords: ['profile', 'account profile'],
    aliases: ['Profile', 'Account'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 1,
  },
  {
    id: 'devices',
    category: 'account',
    title: 'Devices',
    summary: 'Pairing another device with a QR code — real infrastructure, built for future mobile use.',
    overview:
      'PawOS has a real device-pairing system: generate a QR code and a paired device registers itself against ' +
      'your account. This was built as generic pairing infrastructure with a future mobile companion in mind ' +
      '(see Mobile), and requires a real account — Guest sessions cannot pair devices.',
    features: ['QR-code-based device pairing', 'A real device registry per account'],
    howItWorks: 'Open Settings → Devices, generate a pairing QR code, and scan it from the other device to register it against your account.',
    bestPractices: ['Pair devices only from Settings you trust — a paired device is tied to your real account'],
    examples: [],
    troubleshooting: ['If pairing is unavailable, confirm you are signed into a real account, not a Guest session'],
    requirements: ['A real (non-Guest) account'],
    permissions: [],
    relatedArticleIds: ['guest-session', 'mobile'],
    relatedSettings: ['Devices'],
    relatedApps: ['settings'],
    faq: [{ question: 'Can a Guest session pair devices?', answer: 'No — device pairing requires a real account.' }],
    keywords: ['devices', 'device pairing', 'qr code'],
    aliases: ['Devices', 'Pair device'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'account-usage',
    category: 'account',
    title: 'Usage',
    summary: 'Your real AI credit usage against your subscription tier.',
    overview: 'The Usage settings tab shows real, live credit consumption tracked against your tier’s monthly limit — the same underlying data shown in Analytics > AI Usage.',
    features: ['Real usage-this-period tracking', 'Tier-aware credit limit display'],
    howItWorks: 'Every credit-consuming AI action updates this same real usage number.',
    bestPractices: [],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    billing: 'Paw Go has no AI credit pool (0, by design). Other tiers are currently uncapped until specific limits are finalized.',
    relatedArticleIds: ['analytics-ai-usage', 'paw-go'],
    relatedSettings: ['Usage'],
    relatedApps: ['settings', 'analytics'],
    faq: [],
    keywords: ['usage', 'account usage', 'credits'],
    aliases: ['Usage'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 1,
  },
  {
    id: 'account-security',
    category: 'account',
    title: 'Security',
    summary: 'Authentication and password reset for your account.',
    overview:
      'Account-level security covers real hashed passwords for email accounts, real Google OAuth, and a real ' +
      'Forgot Password → one-time code (OTP) → Set New Password flow.',
    features: ['Hashed password storage — never plaintext', 'Real Google OAuth', 'Forgot Password → OTP → Set New Password'],
    howItWorks: 'Choosing "Forgot password" sends a real one-time code to your email; entering it lets you set a new password.',
    bestPractices: ['Use a unique password for your PawOS account', 'Use the Forgot Password flow rather than trying to guess your old password'],
    examples: [{ title: 'Resetting a forgotten password', steps: ['Choose "Forgot password" on the sign-in screen', 'Enter your email', 'Enter the one-time code sent to you', 'Set a new password'] }],
    troubleshooting: ['If the OTP email doesn’t arrive, check spam and confirm the email address is correct'],
    requirements: ['A verified email for the OTP reset flow'],
    permissions: [],
    relatedArticleIds: ['profile', 'security', 'privacy'],
    relatedSettings: ['Account', 'Security'],
    relatedApps: ['settings'],
    faq: [{ question: 'Are my passwords stored in plaintext?', answer: 'No — passwords are hashed, never stored in plaintext.' }],
    keywords: ['security', 'password reset', 'otp', 'forgot password'],
    aliases: ['Forgot Password', 'Reset password'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
];
