import type { HelpArticle } from '../HelpArticleTypes';

export const ANALYTICS_ARTICLES: HelpArticle[] = [
  {
    id: 'analytics-productivity',
    category: 'analytics',
    title: 'Productivity',
    summary: 'What the Analytics section shows today about your activity.',
    overview:
      'Analytics is honestly an early-stage area: a real UI shell with reusable chart containers, populated ' +
      'with genuine data pulled from existing stores (recent activity, task/execution counts) rather than a ' +
      'fully mature analytics product. It shows what actually happened — nothing fabricated — but the ' +
      'breadth of insight will grow over time.',
    features: ['Real recent-activity data pulled from execution history', 'Reusable chart containers ready to be filled in as analytics deepens'],
    howItWorks: 'Analytics reads from the same real stores as Work History and Usage, presenting them in a dashboard layout rather than inventing separate metrics.',
    bestPractices: ['Treat current Analytics as an honest early view, not a complete productivity dashboard yet'],
    examples: [],
    troubleshooting: ['If a chart looks sparse, that reflects genuinely limited activity so far, not a bug'],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['analytics-ai-usage', 'history'],
    relatedSettings: [],
    relatedApps: ['analytics', 'workHistory'],
    faq: [{ question: 'Is Analytics a finished feature?', answer: 'It’s real but early — a working dashboard shell with genuine data, still growing in depth.' }],
    keywords: ['analytics', 'productivity'],
    aliases: ['Analytics', 'Productivity'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'analytics-ai-usage',
    category: 'analytics',
    title: 'AI Usage',
    summary: 'Real credit tracking against your subscription tier’s monthly limit.',
    overview:
      'AI Usage is the most mature part of Analytics: a real credit-tracking system shows how much of your ' +
      'tier’s monthly AI credit allowance you’ve used this period, backed by the same EntitlementService that ' +
      'gates AI model access.',
    features: ['Real per-tier monthly credit limit tracking', 'Usage-this-period display', 'Ties directly to your subscription tier’s entitlements'],
    howItWorks: 'Every AI action that consumes credits records real usage; the Usage settings tab and Analytics both reflect this same real number, never an estimate.',
    bestPractices: ['Check Usage before a heavy AI task if you’re on a capped tier'],
    examples: [],
    troubleshooting: ['If you hit your limit, you’ll see a real, friendly notice rather than a silent failure'],
    requirements: [],
    permissions: [],
    billing: 'Paw Go has a zero AI credit pool by design (no AI models at all). Pro, Pro Max, Team, and Enterprise are currently uncapped until specific limits are finalized.',
    relatedArticleIds: ['analytics-productivity', 'paw-go', 'paw-pro'],
    relatedSettings: ['Usage', 'Billing'],
    relatedApps: ['analytics', 'settings'],
    faq: [{ question: 'What happens when I run out of AI credits?', answer: 'You’ll see a clear, friendly notice rather than an unexplained failure, and can upgrade if you want more.' }],
    keywords: ['ai usage', 'credits', 'usage limit'],
    aliases: ['AI Usage', 'Credits'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'analytics-development',
    category: 'analytics',
    title: 'Development Analytics',
    summary: 'Build, test, and error data surfaced from your real coding activity.',
    overview:
      'Development Analytics reflects the same real build status, test results, and error timeline data shown ' +
      'live in the Coding Canvas during a coding task, aggregated for a broader view of your development ' +
      'activity over time.',
    features: ['Real build/test outcome history', 'Error timeline aggregation'],
    howItWorks: 'Every build, test run, and error event recorded by the Coding Intelligence Runtime feeds this same real data — nothing here is invented or estimated.',
    bestPractices: [],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['build-system', 'debugging', 'analytics-productivity'],
    relatedSettings: [],
    relatedApps: ['analytics', 'development'],
    faq: [],
    keywords: ['development analytics', 'build history', 'test history'],
    aliases: ['Development Analytics'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'project-health',
    category: 'analytics',
    title: 'Project Health',
    summary: 'What real project detection exists today, honestly, without a fabricated health score.',
    overview:
      'There is no dedicated project "health score" system in PawOS today. What is real is the ProjectAnalyzer’s ' +
      'flat metadata detection — framework, language, build tool, and git status — which is what informs the ' +
      'Project Understanding section of the Coding Canvas.',
    features: ['Real framework/language/build-tool/git-status detection per project'],
    howItWorks: 'When you import or open a project, PawOS reads real project files (like package.json) and git state to describe what kind of project it is — a flat description, not a scored assessment.',
    bestPractices: ['Treat project detection as a factual snapshot, not a health score, until a scoring system exists'],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['importing-projects', 'workspaces'],
    relatedSettings: [],
    relatedApps: ['analytics', 'projects'],
    faq: [{ question: 'Does PawOS give my project a health score?', answer: 'Not today — it detects real framework/language/build-tool/git facts, but does not compute a scored health rating yet.' }],
    keywords: ['project health', 'project analyzer'],
    aliases: ['Project Health'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
];
