import type { HelpArticle } from '../HelpArticleTypes';

export const ANALYTICS_ARTICLES: HelpArticle[] = [
  {
    id: 'analytics-productivity',
    category: 'analytics',
    title: 'Productivity',
    summary: 'What the Analytics section shows today about your activity.',
    overview:
      'Analytics is honestly an early-stage area: a real UI shell with reusable chart containers, populated ' +
      'with genuine data pulled from existing stores (recent activity, task/execution counts) rather than a ' +
      'fully mature analytics product. It shows what actually happened — nothing fabricated — but the ' +
      'breadth of insight will grow over time.',
    features: ['Real recent-activity data pulled from execution history', 'Reusable chart containers ready to be filled in as analytics deepens'],
    howItWorks: 'Analytics reads from the same real stores as Work History and Usage, presenting them in a dashboard layout rather than inventing separate metrics.',
    bestPractices: ['Treat current Analytics as an honest early view, not a complete productivity dashboard yet'],
    examples: [],
    troubleshooting: ['If a chart looks sparse, that reflects genuinely limited activity so far, not a bug'],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['analytics-ai-usage', 'history'],
    relatedSettings: [],
    relatedApps: ['analytics', 'workHistory'],
    faq: [{ question: 'Is Analytics a finished feature?', answer: 'It’s real but early — a working dashboard shell with genuine data, still growing in depth.' }],
    keywords: ['analytics', 'productivity'],
    aliases: ['Analytics', 'Productivity'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'analytics-ai-usage',
    category: 'analytics',
    title: 'AI Usage',
    summary: 'Your Paw Compute (PC) usage by activity, and how much of your plan is left.',
    overview:
      'AI Usage shows the Paw Compute (PC) you have used, broken down by activity, together with your plan’s PC ' +
      'for the current billing period, your weekly limit, and any credits you have bought.',
    features: ['PC used by activity', 'Plan PC used and remaining this billing period', 'Weekly limit and credits shown separately'],
    howItWorks: 'PawOS counts Paw Compute on its servers as you use AI; the Usage settings tab and Analytics both show this same number, never an estimate.',
    bestPractices: ['Check Usage before a heavy AI task if you are close to your weekly limit'],
    examples: [],
    troubleshooting: ['If you hit your limit, you’ll see a real, friendly notice rather than a silent failure'],
    requirements: [],
    permissions: [],
    billing: 'Paw Go: 500 PC every 14 days. Pro: 2,000 PC per billing period. Pro Max 5x: 10,000 PC. Pro Max 20x: 25,000 PC. Pro and Pro Max have a weekly limit of half the plan’s PC. Team: per seat — Standard 2,000 PC, Premium 10,000 PC a month (no shared pool). Enterprise: shared organization pool.',
    relatedArticleIds: ['analytics-productivity', 'paw-go', 'paw-pro'],
    relatedSettings: ['Usage', 'Billing'],
    relatedApps: ['analytics', 'settings'],
    faq: [{ question: 'What happens when I reach a limit?', answer: 'You’ll see a clear notice rather than an unexplained failure. At the weekly limit, the rest of your plan becomes available when the weekly limit resets. When your plan’s PC for the period is used up, you can buy credits, upgrade, or wait for your plan to renew.' }],
    keywords: ['ai usage', 'credits', 'usage limit'],
    aliases: ['AI Usage', 'Credits'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'analytics-development',
    category: 'analytics',
    title: 'Development Analytics',
    summary: 'Build, test, and error data surfaced from your real coding activity.',
    overview:
      'Development Analytics reflects the same real build status, test results, and error timeline data shown ' +
      'live in the Coding Canvas during a coding task, aggregated for a broader view of your development ' +
      'activity over time.',
    features: ['Real build/test outcome history', 'Error timeline aggregation'],
    howItWorks: 'Every build, test run, and error event recorded by the Coding Runtime feeds this same real data — nothing here is invented or estimated.',
    bestPractices: [],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['build-system', 'debugging', 'analytics-productivity'],
    relatedSettings: [],
    relatedApps: ['analytics', 'development'],
    faq: [],
    keywords: ['development analytics', 'build history', 'test history'],
    aliases: ['Development Analytics'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
  {
    id: 'project-health',
    category: 'analytics',
    title: 'Project Health',
    summary: 'What real project detection exists today, honestly, without a fabricated health score.',
    overview:
      'There is no dedicated project "health score" system in PawOS today. What is real is the ProjectAnalyzer’s ' +
      'flat metadata detection — framework, language, build tool, and git status — which is what informs the ' +
      'Project Understanding section of the Coding Canvas.',
    features: ['Real framework/language/build-tool/git-status detection per project'],
    howItWorks: 'When you import or open a project, PawOS reads real project files (like package.json) and git state to describe what kind of project it is — a flat description, not a scored assessment.',
    bestPractices: ['Treat project detection as a factual snapshot, not a health score, until a scoring system exists'],
    examples: [],
    troubleshooting: [],
    requirements: [],
    permissions: [],
    relatedArticleIds: ['importing-projects', 'workspaces'],
    relatedSettings: [],
    relatedApps: ['analytics', 'projects'],
    faq: [{ question: 'Does PawOS give my project a health score?', answer: 'Not today — it detects real framework/language/build-tool/git facts, but does not compute a scored health rating yet.' }],
    keywords: ['project health', 'project analyzer'],
    aliases: ['Project Health'],
    pawosVersion: '0.1.0',
    updated: '2026-07-20',
    lastReviewed: '2026-07-20',
    author: 'PawOS Documentation Team',
    readingTimeMinutes: 2,
  },
];
